#include "MidRangeEnemy.h"
#include "GameTimer.h"
#include "Wireframe.h"
#include <imgui.h>
#include <json.hpp>
#include <fstream>
#include <algorithm>
#include <filesystem>
#include <cmath>
using namespace Ken4lowEngine;
void MidRangeEnemy::Initialize(){ EnemyBase::Initialize(); SetCenterPosition({ 3.0f, 2.0f, 20.0f }); LoadFromJson(jsonPath_); }
void MidRangeEnemy::SetTarget(const Vector3& target){ targetPosition_ = target; hasTarget_ = true; }
bool MidRangeEnemy::HasTarget() const{ return hasTarget_; }
void MidRangeEnemy::Update(float deltaTime){ EnemyBase::Update(deltaTime); attackState_.cooldownTimer = std::max(0.0f, attackState_.cooldownTimer - deltaTime); if (attackState_.casting){ attackState_.castTimer += deltaTime; }
 for (auto& bomb : bombs_){ bomb->Update(deltaTime, 0.0f); } bombs_.erase(std::remove_if(bombs_.begin(), bombs_.end(), [](const auto& b){ return !b->IsAlive(); }), bombs_.end()); if (!HasTarget()){ attackState_.lastReason = "ターゲットなし"; return; }
 Vector3 toTarget = targetPosition_ - GetCenterPosition(); const float distXZ = std::sqrt(toTarget.x * toTarget.x + toTarget.z * toTarget.z); if (distXZ > distanceSettings_.detectRange){ attackState_.lastReason = "検知範囲外"; return; }
 Vector3 dir = distXZ > 0.0001f ? Vector3{ toTarget.x / distXZ, 0.0f, toTarget.z / distXZ } : Vector3{ 0.0f, 0.0f, 1.0f }; auto pos = GetCenterPosition(); if (distXZ > distanceSettings_.attackMaxRange){ pos += dir * moveSettings_.moveSpeed * deltaTime; SetCenterPosition(pos); attackState_.lastReason = "接近"; }
 else if (distXZ < distanceSettings_.tooCloseRange){ pos -= dir * moveSettings_.retreatSpeed * deltaTime; SetCenterPosition(pos); attackState_.lastReason = "後退"; }
 else if (distXZ >= distanceSettings_.attackMinRange && distXZ <= distanceSettings_.attackMaxRange){ if (!attackState_.casting && attackState_.cooldownTimer <= 0.0f){ attackState_.casting = true; attackState_.castTimer = 0.0f; attackState_.lastReason = "投擲準備"; }
 if (attackState_.casting && attackState_.castTimer >= attackSettings_.castTime){ auto bomb = std::make_unique<MidRangeBombProjectile>(); bomb->Initialize(); Vector3 start = GetCenterPosition() + Vector3{ 0.0f, attackSettings_.throwHeightOffset, 0.0f }; bomb->Launch(start, targetPosition_, projectileSettings_); bombs_.push_back(std::move(bomb)); attackState_.casting = false; attackState_.castTimer = 0.0f; attackState_.cooldownTimer = attackSettings_.cooldown; attackState_.lastReason = "投擲"; } }
}
void MidRangeEnemy::Draw(){ EnemyBase::Draw(); for (const auto& bomb : bombs_){ bomb->Draw(); } Wireframe::GetInstance()->DrawSphere(GetCenterPosition(), distanceSettings_.detectRange, { 0.3f, 0.9f, 0.9f, 0.2f }); }
void MidRangeEnemy::DrawImGui(){ if (!ImGui::Begin("MidRangeEnemy Debug")){ ImGui::End(); return; } ImGui::Text("中距離敵 基本"); ImGui::DragFloat("検知範囲", &distanceSettings_.detectRange, 0.1f, 1.0f, 100.0f); ImGui::DragFloat("攻撃最小距離", &distanceSettings_.attackMinRange, 0.1f, 0.1f, 50.0f); ImGui::DragFloat("攻撃最大距離", &distanceSettings_.attackMaxRange, 0.1f, 0.1f, 50.0f); ImGui::DragFloat("理想距離", &distanceSettings_.idealRange, 0.1f, 0.1f, 50.0f); ImGui::DragFloat("近すぎる距離", &distanceSettings_.tooCloseRange, 0.1f, 0.1f, 50.0f); ImGui::Separator(); ImGui::Text("移動"); ImGui::DragFloat("移動速度", &moveSettings_.moveSpeed, 0.05f, 0.0f, 20.0f); ImGui::DragFloat("後退速度", &moveSettings_.retreatSpeed, 0.05f, 0.0f, 20.0f); ImGui::DragFloat("回転速度", &moveSettings_.rotateSpeed, 0.05f, 0.0f, 20.0f); ImGui::Separator(); ImGui::Text("爆弾攻撃"); ImGui::DragFloat("攻撃クールダウン", &attackSettings_.cooldown, 0.05f, 0.05f, 10.0f); ImGui::Text("クールダウン残り: %.2f", attackState_.cooldownTimer); ImGui::DragFloat("構え時間", &attackSettings_.castTime, 0.01f, 0.0f, 5.0f); ImGui::Text("構え中か: %s", attackState_.casting ? "はい" : "いいえ"); ImGui::DragFloat("爆弾初速", &projectileSettings_.initialSpeed, 0.05f, 0.1f, 50.0f); ImGui::DragFloat("爆弾上方向速度", &projectileSettings_.upwardVelocity, 0.05f, 0.0f, 50.0f); ImGui::DragFloat("爆弾重力", &projectileSettings_.gravity, 0.05f, 0.1f, 50.0f); ImGui::DragFloat("爆弾寿命", &projectileSettings_.lifeTime, 0.05f, 0.1f, 20.0f); ImGui::DragFloat("直撃判定半径", &projectileSettings_.hitRadius, 0.01f, 0.05f, 10.0f); ImGui::DragFloat("爆発半径", &projectileSettings_.explosionRadius, 0.05f, 0.1f, 20.0f); ImGui::DragInt("直撃ダメージ", &projectileSettings_.directHitDamage, 1, 0, 999); ImGui::DragInt("爆発ダメージ", &projectileSettings_.explosionDamage, 1, 0, 999); ImGui::Text("現在の爆弾数: %d", (int)bombs_.size()); ImGui::Text("最後の行動理由: %s", attackState_.lastReason.c_str()); if (ImGui::Button("保存")){ SaveToJson(jsonPath_); } ImGui::SameLine(); if (ImGui::Button("読み込み")){ LoadFromJson(jsonPath_); } ImGui::Text("保存先: %s", jsonPath_.string().c_str()); ImGui::End(); }
void MidRangeEnemy::SaveToJson(const std::filesystem::path& path) const{ nlohmann::json j; j["distance"] = {{"detectRange", distanceSettings_.detectRange},{"attackMinRange", distanceSettings_.attackMinRange},{"attackMaxRange", distanceSettings_.attackMaxRange},{"idealRange", distanceSettings_.idealRange},{"tooCloseRange", distanceSettings_.tooCloseRange}}; j["move"] = {{"moveSpeed", moveSettings_.moveSpeed},{"retreatSpeed", moveSettings_.retreatSpeed},{"rotateSpeed", moveSettings_.rotateSpeed}}; j["bombAttack"] = {{"cooldown", attackSettings_.cooldown},{"castTime", attackSettings_.castTime},{"throwHeightOffset", attackSettings_.throwHeightOffset}}; j["bombProjectile"] = {{"initialSpeed", projectileSettings_.initialSpeed},{"upwardVelocity", projectileSettings_.upwardVelocity},{"gravity", projectileSettings_.gravity},{"lifeTime", projectileSettings_.lifeTime},{"hitRadius", projectileSettings_.hitRadius},{"explosionRadius", projectileSettings_.explosionRadius},{"directHitDamage", projectileSettings_.directHitDamage},{"explosionDamage", projectileSettings_.explosionDamage},{"directHitAlsoExplosionDamage", projectileSettings_.directHitAlsoExplosionDamage}}; std::filesystem::create_directories(path.parent_path()); std::ofstream ofs(path); ofs << j.dump(4); }
void MidRangeEnemy::LoadFromJson(const std::filesystem::path& path){ std::ifstream ifs(path); if (!ifs.is_open()){ return; } nlohmann::json j; ifs >> j; auto d = j.value("distance", nlohmann::json::object()); distanceSettings_.detectRange = d.value("detectRange", distanceSettings_.detectRange); distanceSettings_.attackMinRange = d.value("attackMinRange", distanceSettings_.attackMinRange); distanceSettings_.attackMaxRange = d.value("attackMaxRange", distanceSettings_.attackMaxRange); distanceSettings_.idealRange = d.value("idealRange", distanceSettings_.idealRange); distanceSettings_.tooCloseRange = d.value("tooCloseRange", distanceSettings_.tooCloseRange); auto m = j.value("move", nlohmann::json::object()); moveSettings_.moveSpeed = m.value("moveSpeed", moveSettings_.moveSpeed); moveSettings_.retreatSpeed = m.value("retreatSpeed", moveSettings_.retreatSpeed); moveSettings_.rotateSpeed = m.value("rotateSpeed", moveSettings_.rotateSpeed); auto a = j.value("bombAttack", nlohmann::json::object()); attackSettings_.cooldown = a.value("cooldown", attackSettings_.cooldown); attackSettings_.castTime = a.value("castTime", attackSettings_.castTime); attackSettings_.throwHeightOffset = a.value("throwHeightOffset", attackSettings_.throwHeightOffset); auto p = j.value("bombProjectile", nlohmann::json::object()); projectileSettings_.initialSpeed = p.value("initialSpeed", projectileSettings_.initialSpeed); projectileSettings_.upwardVelocity = p.value("upwardVelocity", projectileSettings_.upwardVelocity); projectileSettings_.gravity = p.value("gravity", projectileSettings_.gravity); projectileSettings_.lifeTime = p.value("lifeTime", projectileSettings_.lifeTime); projectileSettings_.hitRadius = p.value("hitRadius", projectileSettings_.hitRadius); projectileSettings_.explosionRadius = p.value("explosionRadius", projectileSettings_.explosionRadius); projectileSettings_.directHitDamage = p.value("directHitDamage", projectileSettings_.directHitDamage); projectileSettings_.explosionDamage = p.value("explosionDamage", projectileSettings_.explosionDamage); projectileSettings_.directHitAlsoExplosionDamage = p.value("directHitAlsoExplosionDamage", projectileSettings_.directHitAlsoExplosionDamage); }
