# ---------- Workflow名 ---------- #
name: BuildTests

# ---------- トリガー ---------- #
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

# ---------- 環境変数 ---------- #
env:
  # リポジトリのルートを基準にしたSolutionファイルのパス
  SOLUTION_FILE_PATH: Project/Ken4lowEngine.sln

# ---------- ジョブ ---------- #
jobs:
  build:
    name: Build ${{ matrix.configuration }}

    # Visual Studio 2026とv145 Toolsetが入った公開Repository用Runner
    runs-on: windows-2025-vs2026

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Show MSBuild Version
        run: msbuild -version

      - name: Build ${{ matrix.configuration }}
        run: >
          msbuild "${{ env.SOLUTION_FILE_PATH }}"
          /m
          /t:Rebuild
          /p:Platform=x64
          /p:Configuration=${{ matrix.configuration }}
          /verbosity:minimal
